# Spring Data
spring:
  datasource:
    url: ${env.JDBC_CONNECTOR}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${env.DB_INIT}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true

# Spring Security

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:app-veterinario.p12
    key-store-type: PKCS12
    key-store-password: changeit

# Debug
#debug=true
#spring.jpa.show-sql=true
