# Spring Data
spring:
  datasource:
    url: "jdbc:mysql://db:3306/app_veterinario?useTimezone=true&serverTimezone=America/Sao_Paulo&autoReconnect=true"
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

# Spring Security

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:app-veterinario.p12
    key-store-type: PKCS12
    key-store-password: changeit

# Debug
#debug=true
#spring.jpa.show-sql=true
